### ISSUE TITLE
Turn off CONFIG_ZMK_WIDGET_LAYER_STATUS

### ISSUE THREAD

**Issue by soodoh** [LOWPROKB/zmk-config-zen-2#2]
Loving my new corneish zen so far, but still tweaking the firmware to get it how i like. Since e-ink displays are pretty slow to refresh, I would like to turn off the layer status on the display since it's not super helpful since I am mainly using momentary toggles to switch layers. I also think it may (very slightly) improve my battery life since it won't be updating the display as often.

Unfortunately, when I update `corneish_zen.conf` to set `CONFIG_ZMK_WIDGET_LAYER_STATUS=n`, I am still seeing the layer widget on the display.

Is this a known bug? How can I change the display settings as documented in the official ZMK documentation?

**Comment by caksoylar** [comment]
Hi there, you need to use a different Kconfig key to disable that, [`CONFIG_CUSTOM_WIDGET_LAYER_STATUS=n`](https://github.com/LOWPROKB/zmk/blob/corne-ish-zen-v2/app/boards/arm/corneish_zen/Kconfig.defconfig#L75). What you used disables the non-custom version of the widget which is in stock ZMK.

By the way you might get faster help from the [lowprokb Discord](https://discord.com/invite/tuQrXRzt) (also on https://lowprokb.ca); I only happened to see this randomly 😄

**Comment by soodoh** [comment]
Amazing, thanks for your response.

I’m a part of the Discord, but don’t use it much. I’ll be sure to check there next time!

**Comment by arialdomartini** [comment]
@pauldiloreto notice that in order to use that option (part of @caksoylar's [Display improvements for the Corne-ish Zen keyboard](https://gist.github.com/caksoylar/c411313990978e1903c244f03039187a)) you will need to update your `west.yml` to

```yaml
manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: caksoylar
      url-base: https://github.com/caksoylar
  projects:
    - name: zmk
      remote: caksoylar
      revision: caksoylar/zen-v2
      import: app/west.yml
  self:
    path: config
```
